### ISSUE TITLE
scripts must be memorized

### ISSUE THREAD

**Issue by CaptainCorin100** [davidferguson/itemswap#3]

**Comment by CaptainCorin100** [comment]
I still haven't closed this yet.

**Comment by CaptainCorin100** [comment]
We have had over a year to memorise them and we failed.

**Comment by CaptainCorin100** [comment]
Shameful

**Comment by CLBirch** [comment]
Yes.

**Comment by davidferguson** [comment]
I did memorise it for last year, so maybe this can be closed? And seeing as we _did_ win, this issue obviously wasn't too serious.

**Comment by CLBirch** [comment]
no
do not close it

**Comment by CLBirch** [comment]
_**Coffee.**_
I felt that comment was necessary.
Now you can close it.

**Comment by davidferguson** [comment]
![out](https://user-images.githubusercontent.com/13520342/29141333-b9b4301a-7d45-11e7-9f72-181a21f4b34b.gif)

**Comment by CaptainCorin100** [comment]
I think if we had managed this issue beforehand we would've won better
